export const YOUTUBE_SEED_CATEGORIES = [
  'Music',
  'Gaming',
  'Education',
  'Lifestyle',
  'Tech',
  'Comedy',
  'Travel',
  'Food',
  'News',
  'Fitness',
];

export const YOUTUBE_SEED_LOCATIONS = [
  'United States',
  'Canada',
  'United Kingdom',
  'India',
  'Brazil',
  'Germany',
  'Australia',
  'Japan',
  'South Africa',
  'France',
];

export const YOUTUBE_SEED_CHANNEL_NAMES = [
  'Ava Brooks',
  'Miles Carter',
  'Zoe Patel',
  'Nathan Lee',
  'Luna Martinez',
  'Ethan Walker',
  'Sofia Nguyen',
  'Lucas Kim',
  'Chloe Adams',
  'Noah Thompson',
  'Mia Johnson',
  'Daniel Garcia',
  'Harper Smith',
  'Benjamin Davis',
  'Ella Wilson',
  'James Brown',
  'Amelia Moore',
  'Leo Anderson',
  'Scarlett White',
  'Henry Clark',
  'Grace Lewis',
  'Jack Hall',
  'Avery Young',
  'Liam Allen',
  'Layla Scott',
  'Oliver King',
  'Bella Green',
  'Wyatt Baker',
  'Charlotte Perez',
  'Mateo Torres',
  'Aria Flores',
  'David Evans',
  'Madison Collins',
  'Samuel Rivera',
  'Hannah Reed',
  'Gabriel Perez',
  'Nora Stewart',
  'Julian Ward',
  'Emily Foster',
  'Leo Carter',
  'Penelope Hughes',
  'Aiden Ramirez',
  'Stella Cooper',
  'Isaac Price',
  'Victoria Foster',
  'Theodore Reed',
  'Ruby Murphy',
  'Connor Bell',
  'Paisley Ross',
  'Hudson Bailey',
  'Addison Brooks',
  'Eli Hughes',
  'Aurora Cox',
  'Ryan Flores',
  'Savannah Ross',
  'Dylan Jenkins',
  'Camila Murphy',
  'Anthony Ward',
  'Claire Coleman',
  'Mason Clark',
  'Naomi Howard',
  'Adrian Foster',
  'Skylar Sanders',
  'Jose Rivera',
  'Samantha Price',
  'Leo Brooks',
  'Kylie Turner',
  'Jonathan Hughes',
  'Aria James',
  'Sebastian Torres',
  'Lily Gray',
  'Christopher Nelson',
  'Bella Wells',
  'Isaiah Morgan',
  'Hazel Hall',
  'Colton Powell',
  'Elena Murphy',
  'Nathan Allen',
  'Eva Peterson',
  'Oscar Bennett',
  'Madeline Ward',
  'Andrew Martin',
  'Layla Coleman',
  'Jordan Perry',
  'Ruby Sanders',
  'Tyler Baker',
  'Alyssa Kelly',
  'Carter Hughes',
  'Mila Thompson',
  'Julian Ross',
  'Ivy Scott',
  'Kai Foster',
  'Piper Johnson',
  'Asher Phillips',
  'Zoey Adams',
  'Gavin Cole',
  'Lucy Moore',
  'Elijah Bailey',
  'Maya Jenkins',
  'Joseph Lee',
  'Ariana Reed',
  'Lincoln Kelly',
  'Cora Parker',
  'Wyatt Murphy',
  'Amaya Ross',
  'Adrian Perez',
  'Violet Simmons',
  'Logan Wright',
  'Nina Brooks',
  'Isaac Foster',
  'Chloe Nelson',
  'Mateo Bennett',
  'Sophie Foster',
  'Nathan Adams',
  'Harper Davis',
  'Xavier Green',
  'Aubrey Price',
  'Caleb Turner',
  'Holly Parker',
  'Daniel James',
  'Scarlett Collins',
  'Julian Wood',
  'Zara Hill',
  'Owen Bennett',
  'Isla Murphy',
  'Isaac Ward',
  'Riley Cooper',
  'Thomas Evans',
  'Aria Hughes',
  'Ryder Nelson',
  'Lila Cox',
  'Henry Price',
  'Gracie Lopez',
  'Evan Reed',
  'Mila Hughes',
  'Weston Brooks',
  'Aurora Lewis',
  'Derek Scott',
  'Sienna Murphy',
  'Adam Harris',
  'Naomi Flores',
  'Nicholas Wilson',
  'Zoey Perry',
  'Milo Torres',
  'Ella Campbell',
  'Carson Young',
  'Rosalie Price',
  'Hudson Brooks',
  'Vivian Flores',
  'Cameron Rivera',
  'Leah Ward',
  'Marcus Cox',
  'Penelope Hill',
  'Eli Cooper',
  'Layla Howard',
  'Luca Bryant',
  'Mila Fernandez',
  'Roman Perry',
  'Jade Long',
  'Omar Flores',
  'Madison Brooks',
  'Theo Sanders',
  'Hannah Price',
  'Brandon Green',
  'Lola Hall',
  'Julian Foster',
  'Eva Bennett',
  'Mason Campbell',
  'Sadie Harris',
  'Kai Murphy',
  'Gianna Cox',
];
